FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Устанавливаем serve для раздачи статики
RUN npm install -g serve

EXPOSE 4444

CMD ["serve", "-s", "docs", "-l", "4444"]
